# Generated by Django 3.1 on 2020-09-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0002_auto_20200902_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='adminCountry',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='franchiseprofile',
            name='franchiseCountry',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='instituteprofile',
            name='instituteCountry',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='trainerCountry',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='franchiseprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
