# Generated by Django 3.1 on 2020-09-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200, null=True)),
                ('courseDescription', models.CharField(max_length=2000, null=True)),
                ('courseCategory', models.CharField(blank=True, choices=[('course1', (('Course 1.1', 'Course 1.1'), ('Course 1.2', 'Course 1.2'), ('Course 1.3', 'Course 1.3'))), ('course2', (('Course 2.1', 'Course 2.1'), ('Course 2.2', 'Course 2.2'))), ('course3', (('Course 3.1', 'Course 3.1'), ('Course 3.2', 'Course 3.2')))], max_length=200, null=True)),
                ('courseOnline', models.BooleanField(blank=True, default=False, null=True)),
                ('courseLive', models.BooleanField(blank=True, default=False, null=True)),
                ('courseOffline', models.BooleanField(blank=True, default=False, null=True)),
                ('courseStatus', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=30, null=True)),
                ('coursePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courseCity', models.CharField(max_length=200, null=True)),
                ('courseState', models.CharField(max_length=200, null=True)),
                ('courseCountry', models.CharField(max_length=200, null=True)),
                ('courseBelong', models.CharField(blank=True, choices=[('Trainer', 'Trainer'), ('Intitute', 'Institute'), ('Franchise', 'Franchise')], max_length=30, null=True)),
                ('courseAddedDate', models.DateTimeField(auto_now_add=True)),
                ('courseVideoName', models.CharField(blank=True, max_length=500, null=True)),
                ('courseVideoFile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
