# Generated by Django 3.1 on 2020-09-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('multiuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multiuser.franchiseprofile'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multiuser.instituteprofile'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multiuser.trainerprofile'),
        ),
    ]
