# Generated by Django 3.1 on 2020-09-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200902_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='courseCountry',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
