# Generated by Django 3.1 on 2020-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_invoice_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-invoice_date', 'id')},
        ),
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(default=2, max_length=34),
            preserve_default=False,
        ),
    ]
