# Generated by Django 3.1 on 2020-09-02 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TS', 'Transgender')], max_length=50)),
                ('student_profilepic', models.FileField(upload_to='')),
                ('stdent_Email', models.EmailField(max_length=111)),
                ('student_created_at', models.DateTimeField(auto_now_add=True)),
                ('student_PhoneNo1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('student_PhoneNo2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('student_Street', models.CharField(default='', max_length=250)),
                ('student_Landmark', models.CharField(default='', max_length=100)),
                ('student_Zipcode', models.IntegerField(default='')),
                ('student_State', models.CharField(default='', max_length=100)),
                ('student_Country', models.CharField(default='', max_length=100)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.coursedetails')),
                ('student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
